### ISSUE TITLE
Support for spring-boot lifecycle

### ISSUE THREAD

**Issue by abashev** [takari/takari-lifecycle#10]
Right now it is not possible to use spring-boot plugin out-the-box with takari lifecycle. Faster incremental builds will be very useful with `spring-boot:run` maven task

**Comment by ifedorenko** [comment]
You probably want to provide small standalone example project and description of the desired behaviour. Direct support for Spring is probably out of scope of takari-lifecycle, but maybe there is a common pattern we can support.

**Comment by abashev** [comment]
Sorry for little delay, there is minimal spring-boot project https://gist.github.com/abashev/c3d41f8681df09b5598c

It contains two files - one is pom.xml and Application.java from `src/main/java/boot` directory. It works fine with `compile` and `spring-boot:run` targets. But if I turn on `<packaging>takari-jar</packaging>` and try to do `mvn clean package` then I see this error message

```
[INFO] --- takari-lifecycle-plugin:1.10.2:jar (default-jar) @ takari-boot ---
[INFO] Previous incremental build state does not exist, performing full build
[INFO] Building main JAR.
[INFO]
[INFO] --- spring-boot-maven-plugin:1.2.1.RELEASE:repackage (default) @ takari-boot ---
[INFO] Attaching archive: /Users/abashev/takipi-boot/target/takari-boot-1.0.0-SNAPSHOT.takari-jar, with classifier: null
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.538 s
[INFO] Finished at: 2015-02-08T19:19:42+03:00
[INFO] Final Memory: 29M/358M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.springframework.boot:spring-boot-maven-plugin:1.2.1.RELEASE:repackage (default) on project takari-boot: Execution default of goal org.springframework.boot:spring-boot-maven-plugin:1.2.1.RELEASE:repackage failed: For artifact {takari-boot:takari-boot:1.0.0-SNAPSHOT:takari-jar}: An attached artifact must have a different ID than its corresponding main artifact. -> [Help 1]
[ERROR]
```

**Comment by abashev** [comment]
Ok, I found a little workaround for spring-boot plugin

```
          <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <executions>
                    <execution>
                        <goals>
                            <goal>repackage</goal>
                        </goals>
                        <configuration>
                            <classifier>exec</classifier>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
```
In this case final artifact name will be something like - `takari-boot-1.0.0-SNAPSHOT-exec.takari-jar` but it is still jar file and it could be used to start the application

I don't think you need to fix something internally but it could be a good example of 'how to use takari with Spring Boot'

**Comment by ifedorenko** [comment]
This is a bug in spring-boot-maven-plugin, it assumes that artifact type and extension are the same thing and mishandles main project artifacts when type and extensions do not match. Offending code is in `org.springframework.boot.maven.RepackageMojo#execute()` around line 175. Nothing we can do from takari-lifecycle end. I suggest you report this to Spring developers.
