### ISSUE TITLE
Error messages of the compile goal

### ISSUE THREAD

**Issue by sviperll** [takari/takari-lifecycle#15]
Original maven-compiler-plugin writes error messages as:

````
com/domain/Class1.java[10,10]: error
````

But takari `compile` goal writes full path:

````
/home/foo/bar/src/main/java/com/domain/Class1.java[10,10]: error
````

This prevents Netbeans (and possibly IDEA) integration.

**Comment by ifedorenko** [comment]
When I troubleshoot builds on command line or in CI, I find it more convenient to see full paths to the sources in error messages. This way I can easily copy&paste the path to open the editor for example.

**Comment by sviperll** [comment]
I'm trying to investigate lack of IDE support for takari.

It seems to me that maven-compiler-plugin behaves differently in different environments. When run from command line it outputs full path, but when run from Netbeans it outputs relative path to source root.

Netbeans highlights references to source files only when relative path is used...

**Comment by sviperll** [comment]
It seems to be Netbeas problem and not takari's.

Netbeans parses full paths and replaces them with hyperlinks with relative paths. See [JavaOutputListenerProvider.java](http://hg.netbeans.org/main/file/0877331f85a8/maven/src/org/netbeans/modules/maven/output/JavaOutputListenerProvider.java). The fix seems to be adding additional `JAVAGOAL` to this file:

````java
    private static final String[] JAVAGOALS = new String[] {
        "mojo-execute#compiler:compile", //NOI18N
        "mojo-execute#compiler:testCompile", //NOI18N
        "mojo-execute#takari-lifecycle-plugin:compile", //NOI18N
        "mojo-execute#takari-lifecycle-plugin:testCompile" //NOI18N
    };
````

**Comment by ifedorenko** [comment]
closing as per last comment

**Comment by sviperll** [comment]
Thank you for your work on takari. It seems really promising!

Besides, I have filed a bug report for Netbeans about integration with takari.
