### ISSUE TITLE
missing Build-Jdk-Spec entry in META-INF/MANIFEST.MF makes Reproducible Builds check hard

### ISSUE THREAD

**Issue by hboutemy** [takari/takari-lifecycle#177]
maven-jar-plugin defines `Build-Jdk-Spec: xxx` in `META-INF/MANIFEST.MF`, which helps a lot discovering the JDK used to build a `.jar` (and makes publishing generated buildspec or buildinfo to Maven Central not really useful: we have the info through `Build-Jdk-Spec`)
Takari Lifecycle currently does not store any hint, which makes guessing the JDK to use to check Reproducible Builds hard

**Comment by cstamas** [comment]
:+1: 
Will add it.
