### ISSUE TITLE
io.takari.maven.plugins.compile.jdt.FilerImpl#getResource(StandardLocation.CLASS_PATH, ...)

### ISSUE THREAD

**Issue by sviperll** [takari/takari-lifecycle#18]
`getResource` method seems not to work when location is set to StandardLocation.CLASS_PATH.

I expect this method to search all classpath entries to find file with given name.

When compiler is set to `javac` everything works as described above.
When compiler is set to `jdt` `FilerImpl#getResource` method seems to look at single directory only and fail to find resource.

If resource is located in output directory, location can be set to StandardLocation.CLASS_OUTPUT as a work around.

**Comment by ifedorenko** [comment]
FWIW, compliant `Filer` implementation is only required to support `StandardLocation#CLASS_OUTPUT` and `StandardLocation#SOURCE_OUTPUT` locations. At very least jdt FileImpl must throw `IllegalArgumentException` but I'll see what it takes to support `StandardLocation.CLASS_PATH` too.

**Comment by ifedorenko** [comment]
Beware of https://bugs.eclipse.org/bugs/show_bug.cgi?id=466878

**Comment by sviperll** [comment]
Thank you for your work!
