### ISSUE TITLE
takari-lifecycle-plugin not support Lombok annotation?

### ISSUE THREAD

**Issue by nathanyan** [takari/takari-lifecycle#2]
I have a maven project, use Lombok  generate set/get method. when I use takari-lifecycle-plugin compile ,class not generate set/get method. 

I think the Lombok  not work

**Comment by jvanzyl** [comment]
Annotation processing is off by default, but if you turn annotation processing on Lombok works fine:

https://github.com/takari/project-with-lombok

**Comment by ifedorenko** [comment]
Changed compile mojo to require explicit <proc> value of annotation processors are present on classpath.

https://github.com/takari/takari-lifecycle/commit/c9947e4f0f5da5703dcb2056ab7e3bbc7d26f36b

**Comment by velo** [comment]
nice!
