### ISSUE TITLE
Takari with parallel build

### ISSUE THREAD

**Issue by testn** [takari/takari-lifecycle#32]
When I run takari-lifecycle enabled maven project with `mvn -T 4 install`, sometimes, I get the error 
```
[INFO] Performing incremental build
[ERROR] ............: ........ cannot be resolved to a type
[ERROR] ............: ........ cannot be resolved to a type
[ERROR] ............: ........ cannot be resolved to a type
[ERROR] ............: ........ cannot be resolved to a type
```

if I run it without `-T 4`, it works fine every time.

**Comment by jvanzyl** [comment]
We need a sample project to reproduce this condition. Please reopen with a sample project and we'll try to reproduce ourselves.
