### ISSUE TITLE
Not compatible with SonarQube plugin

### ISSUE THREAD

**Issue by henryju** [takari/takari-lifecycle#35]
Hi guys,

One of our user reported he can't use takari lifecycle + SonarQube Maven plugin (sonar:sonar). This goal is supposed to be an aggregator so only executed on root project but with takari it seems to be executed on each module.

See the original report (with a reproducer):
https://groups.google.com/d/msg/sonarqube/3HApUrDEnyE/ApWZciGRBgAJ

For me this is a bug of takari lifecycle but please tell me if I'm wrong.

**Comment by ifedorenko** [comment]
You probably meant https://github.com/takari/takari-smart-builder, not takari-lifecycle.

**Comment by henryju** [comment]
Oups, sorry. I'll reopen there: https://github.com/takari/takari-smart-builder/issues/3
