### ISSUE TITLE
Support creating bundles

### ISSUE THREAD

**Issue by kwin** [takari/takari-lifecycle#37]
The https://github.com/bndtools/bnd/tree/master/maven/bnd-maven-plugin is creating the manifest which is then used by the maven-jar-plugin. Is it possible to combine that with the takari-lifecycle-plugin?
Especially interesting for bundles is this feature: http://takari.io/book/40-lifecycle.html#enforcing-dependency-usage-during-compilation.

**Comment by ifedorenko** [comment]
Takari lifecycle does support custom jar manifest

```xml
        <groupId>io.takari.maven.plugins</groupId>
        <artifactId>takari-lifecycle-plugin</artifactId>
        <configuration>
          <archive>
            <manifestFile>${project.basedir}/src/META-INF/MANIFEST.MF</manifestFile>
          </archive>
        </configuration>
      </plugin>
```

I don't know if bnd-maven-plugin provides correct incremental build behaviour or idempotency guarantees.

**Comment by gtnarg** [comment]
Is this documented?

I tried the following and it failed.

 ```
<archive>
	<manifestEntries>
		<myEntry>test</myEntry>
	</manifestEntries>
</archive>
```

**Comment by gtnarg** [comment]
Does the custom jar manifest merge with the generated manifest as done in the maven-archiver?

https://maven.apache.org/shared/maven-archiver/examples/manifestFile.html
