### ISSUE TITLE
typo: Lifecycle doc

### ISSUE THREAD

**Issue by bhamail** [takari/takari-lifecycle#4]
I couldn't find a related git repo to make a PR, so just posting this here. Apologies if this is the wrong place.

I this page: http://takari.io/book/40-lifecycle.html
there is a typo: "tje" should be: "as the".

Current: 
This reduces the download times to retrieve the needed components as well tje storage space requirements in your repositories.

should be:
This reduces the download times to retrieve the needed components as well as the storage space requirements in your repositories.

**Comment by jvanzyl** [comment]
Thanks, fixed and published.
