### ISSUE TITLE
process-resources filtering replaces undefined properties with empty string

### ISSUE THREAD

**Issue by seanf** [takari/takari-lifecycle#40]
Takari's process-resources and process-test-resources goals, when filtering is active, replace unknown/undefined properties with the empty string. The standard resources plugin seems to leave unrecognised properties as is.

Depending on this behaviour is probably a bad idea, but the difference can make migration difficult.

**Comment by seanf** [comment]
Related: https://issues.apache.org/jira/browse/MRESOURCES-162

**Comment by ifedorenko** [comment]
I wonder if the build should fail due to unknown/undefined `${properties}`.

**Comment by seanf** [comment]
Well, if you have a build which depends on the (questionable) behaviour of maven-resources-plugin, it can be very difficult to migrate to takari-lifecycle-plugin unless it has _some_ way of emulating that behaviour.

I think it would be quite manageable if the default behaviour were to fail the build in the case of undefined properties (strict mode), as long as there was an _option_ to leave undefined properties untouched without failing the build (passthrough mode).

There might be a use case for the (takari-specific?) behaviour of replacing undefined properties with the empty string too (um, null mode?). Not sure. Maybe this case can be handled by giving those properties empty defaults in the project's properties.

I think the general rule in Maven for undefined property substitutions is to leave them as is, but I can't find anything in the documentation to back that up. I just seem to remember Maven has created a number of silly files with names like `${some.variable}` in my `target` directories.

If an option were out of the question, strict mode at least would make it easy to identify the problem, by virtue of failing fast.

**Comment by jakub-bochenski** [comment]
Shouldn't this be closed since #59 was merged?

**Comment by ifedorenko** [comment]
yes, I think you are right.
