### ISSUE TITLE
Full build instead of incremental

### ISSUE THREAD

**Issue by Gustu** [takari/takari-lifecycle#49]
Hi,

I've added to my project this plugin and I have problem with incremental building. It's not doing incremental build at all. It always builds whole modules if something has changes and what's weird it's not skipping unchanged modules sometimes.

This is my plugin configuration:

```
<plugin>
                <groupId>io.takari.maven.plugins</groupId>
                <artifactId>takari-lifecycle-plugin</artifactId>
                <version>1.12.4</version>
                <extensions>true</extensions>
                <executions>
                    <execution>
                        <id>compile</id>
                        <goals>
                            <goal>compile</goal>
                            <goal>testCompile</goal>
                        </goals>
                        <configuration>
                            <proc>proc</proc>
                            <compilerId>javac</compilerId>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
```
It's in parent POM file.

I use Lombok annotations and I cannot use JDT compiler. Maybe javac compiler causes those full builds.

**Comment by ifedorenko** [comment]
`javac` indeed forces "coarse-grained" incremental behaviour, the compile mojo will do nothing if there are no changes but will compile everything if there are any changes in sources or dependencies.

unlike `jdt`, `javac` does not provide type reference information required to determine recompilation scope during incremental build, so the only way to guarantee correct build results is to recompile everything if there are any changes.
