### ISSUE TITLE
How to get an indicator that no source code is being compiled by takari-lifecycle-plugin?

### ISSUE THREAD

**Issue by mallim** [takari/takari-lifecycle#6]
I am using takari-lifecycle-plugin to compile and package a set of EJB source code, after which I will invoke wls-maven-plugin:appc to precompile the EJB.

Is there a way for me to detect takari-lifecycle-plugin has not compile any source code? I can thus use the information to skip wls-maven-plugin:appc

````
            <plugin>
                <groupId>com.oracle.weblogic</groupId>
                <artifactId>wls-maven-plugin</artifactId>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>appc</goal>
                        </goals>
                    </execution>
                </executions>
        </plugin>
````

**Comment by ifedorenko** [comment]
Short answer is no, you can't do this without changes to wls-maven-plugin.

Current Maven plugin API does not have enough metadata to implement build avoidance logic externally, without changing plugins in question. We have some ideas how to do this in future versions of Maven plugin API, but this is likely several years off. 

The only way to implement build avoidance today is to change wls-maven-plugin. I can give some pointers if you are in position to try this.
