### ISSUE TITLE
Support altDeploymentRepository for deploy

### ISSUE THREAD

**Issue by jvanzyl** [takari/takari-lifecycle#7]
Currently altDeploymentRepository is not supported for deployment which is used in conjunction with release:stage.

**Comment by ifedorenko** [comment]
Fixed by ddf7eb6152132dcd0c223dc3203acbb39d572c11

**Comment by delanym** [comment]
Not working on v2.0.7. It wants the old Maven 2 syntax of "id::layout::url".
I rerun command and it complains about authentication.

**Comment by jvanzyl** [comment]
Can you provide a reproducer project?

**Comment by delanym** [comment]
@jvanzyl git@github.com:delanym/maven-repository-tools.git

**Comment by mosabua** [comment]
Hahah .. @delanym .. if you have any changes for my maven-repository-tools  just send me a PR and I can cut a release

**Comment by delanym** [comment]
@mosabua will do

@jvanzyl can you reopen ticket, or should I make another one?
