### ISSUE TITLE
PluginDescriptorMojo.writeLifecycleMappingMetadata should include groupId, artifactId and version

### ISSUE THREAD

**Issue by cvgaviao** [takari/takari-lifecycle#71]
After moving to Oxygen recently I started to receive some error messages about a **pluginExecutionFilter** do not have an groupId, artifactId and version.
That error was happen while setting a pom and adding a plugin created using takari-maven-plugin packaging.

> Errors occurred during the build.
Errors running builder 'Maven Project Builder' on project 'c8tech-repository'.
Missing parameter for pluginExecutionFilter. groupId, artifactId, versionRange and goals must be specificed, but found: goals = '[]'

I did some investigation and discover that in some cases takari-plugin is creating or rewriting the **/META-INF/m2e/lifecycle-mapping-metadata.xml** for me, but it is missing those data (that wasn't required before). 
bellow is the one being rewritten since I have one at **/src/main/resources-filtered/META-INF/m2e/lifecycle-mapping-metadata.xml**

```
<?xml version="1.0" encoding="UTF-8"?>

<!-- Generated by PluginDescriptorMojo -->

<lifecycleMappingMetadata>
  <pluginExecutions>
    <pluginExecution>
      <pluginExecutionFilter>
        <goals/>
      </pluginExecutionFilter>
      <action>
        <configurator>
          <id>io.takari.m2e.incrementalbuild.builderMojoExecutionConfigurator</id>
        </configurator>
      </action>
    </pluginExecution>
  </pluginExecutions>
</lifecycleMappingMetadata>
```

**Comment by cvgaviao** [comment]
I'm attaching a sample that shows the problems. 
[test-mojo.zip](https://github.com/takari/takari-lifecycle/files/2087326/test-mojo.zip)

**Comment by ifedorenko** [comment]
groupId, artifactId and version should not be required when lifecycle mapping metadata is embedded in a plugin (m2e retrieves the metadata from a plugin jar, so it already knows everything about the plugin). something else is broken or misbehaving.

**Comment by cvgaviao** [comment]
well, so it is something related to m2e, because only after I have opened the jar in the .m2 directory and directed rewrite the xml, the plugin was recognized correctly in the ide.
but anyway, lifecycle-plugin wouldn't rewrite my own provided file, don't you think ?

**Comment by ifedorenko** [comment]
right, this looks like an m2e bug, it supposed to use plugin groupId, artifactId and version when reading lifecycle metadata from plugin jar.
