### ISSUE TITLE
lombok is not compatible with compilerId=jdt

### ISSUE THREAD

**Issue by f0rmatme** [takari/takari-lifecycle#79]
"You aren't using a compiler supported by lombok, so lombok will not work and has been disabled."

Any way around this? Seems like switching to javac fixes it but defeats the purpose of takari?

**Comment by ifedorenko** [comment]
Not sure, tbh. Lombok [claims compatibility with Eclipse java compiler](https://projectlombok.org/setup/ecj) now, but I have not looked at how it is implemented and if it can work with Takari Lifecycle.

**Comment by f0rmatme** [comment]
https://stackoverflow.com/questions/24006937/lombok-annotations-do-not-compile-under-intellij-idea/30125507#30125507

going to try this, leaving it hear for anyone else with this issue.

**Comment by ZijieSong** [comment]
> Not sure, tbh. Lombok [claims compatibility with Eclipse java compiler](https://projectlombok.org/setup/ecj) now, but I have not looked at how it is implemented and if it can work with Takari Lifecycle.

hi, any progress now? thanks!!
