### ISSUE TITLE
Update check seems broken

### ISSUE THREAD

**Issue by cstamas** [takari/takari-lifecycle#80]
The `update-check` mojo blocks the build for quite a while. It seems that `update-check` tries to contact `https://update.takari.io/latest/takari-lifecycle` but server is down/timeouts?

**Comment by ifedorenko** [comment]
`update.takari.io` was shut down long time ago, `update-check` does nothing now (it's expected to silently ignore connection errors).

**Comment by cstamas** [comment]
I understand the shut down part. What annoys me is the huge delay until life-cycle continues the build, as the whole build stalls, in same way as curl does (2min):

```
cstamas@Urnebes ~ $ time curl https://update.takari.io/latest/takari-lifecycle
curl: (7) Failed to connect to update.takari.io port 443: Connection timed out

real	2m10,078s
user	0m0,014s
sys	0m0,006s
cstamas@Urnebes ~ $ 
```

**Comment by ifedorenko** [comment]
this is odd. update check should only work once a week and should not block for more than 30 seconds. in any case, I'll try to find time to remove the update check in the next few days but no promise. I also don't know if I still have the powers to do takari-lifecycle releases, so it may not be much help even  if I remote it.

**Comment by mosabua** [comment]
If necessary I can cut a release as well but you still should be all set @ifedorenko
