### ISSUE TITLE
path escape backslash

### ISSUE THREAD

**Issue by tonycody** [takari/takari-lifecycle#99]
> properties file

```shell
log=${project.build.directory}${file.separator}logs
applog=${project.build.directory}
```

> mvn clean package target file

```shell
log=C:\Users\XS\IdeaProjects\sample\target\logs
applog=C:\Users\XS\IdeaProjects\sample\target
```

> Why isn't the output this?
> There are no configuration parameters to control.
```shell
log=C:\\Users\\XS\\IdeaProjects\\sample\\target\\logs
applog=C:\\Users\\XS\\IdeaProjects\\sample\\target
```

![image](https://user-images.githubusercontent.com/6773121/98890479-05466480-24d7-11eb-9191-d7e4c6c6d3ee.png)
[sample.zip](https://github.com/takari/takari-lifecycle/files/5528008/sample.zip)

**Comment by mosabua** [comment]
Your screenshot shows you are using the resources plugin .. not takari lifecycle

**Comment by tonycody** [comment]
> Your screenshot shows you are using the resources plugin .. not takari lifecycle

you try.

**Comment by tonycody** [comment]
> Your screenshot shows you are using the resources plugin .. not takari lifecycle

I tried the official Demo and it's the same thing

**Comment by tonycody** [comment]
@mosabua i check source code,Only some variables support conversion to '/'
The built-in variables are displayed as file instead of String
